### ISSUE TITLE
PSD gradient wrong?

### ISSUE THREAD

**Issue by matbesancon** [matbesancon/MathOptSetDistances.jl#18]
The gradient of projection onto PSD cone seems to fail for most random negative definite matrices. This had not been tested by previous tests

**Comment by matbesancon** [comment]
@joaquimg, @blegat opinions?

**Comment by joaquimg** [comment]
First, thing we should reference the cvxpy implementation from that:
https://github.com/cvxgrp/diffcp/blob/ef301811feede5cebb4659598e6b4de822e7a1e0/cpp/src/cones.cpp#L238
It is very similar.
Second, one thing I could not from start is that we a missing a `k-=1`
because as in the code: ` # k is the number of negative eigenvalues in X minus ONE`
Finally, we should think more about that `1e-4`.
Eigensolver should have larger precision very often (cvxpy even uses 0).
We should consider reducing and having that as a function default parameter.

**Comment by joaquimg** [comment]
There is more:
we are not taking advantage of symmetry in `unvec_symm`, which could make a difference for eigensolver.

And I haven't seen any correction factor in conversions of matrix to vector form, we might need some `sqrt(2)` in some places...
@blegat is the master of that.

**Comment by matbesancon** [comment]
seems all good. @joaquimg we should add a performance issue to track the unvec you mentioned above
